config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"

  get '/posts/search' => 'posts#search', :as => 'search_posts'

  get '/users/show' => 'user#show', :as => 'show_users'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments, dependent: :destroy
  has_one_attached :picture, dependent: :destroy

  VALID_CATEGORIES = ['Scientific', 'Politics', 'TV Series', 'Anime', 'Films', 'Technologies', 'Music', 'Other', 'Sport']

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :category, presence: true, inclusion: {in: VALID_CATEGORIES}
  validates :picture, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: :author_id, inverse_of: :author
  has_many :comments, foreign_key: :author_id, inverse_of: :author

  ROLES = {
    user: 0,
    admin: 1
  }.with_indifferent_access.freeze

  enum role: ROLES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end

  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[ create destroy ]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(:author_id => current_user.id))
    @comment.author = current_user
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    authorize @comment
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  POSTS_PER_PAGE = 5
  before_action :authenticate_user!, only: %i[ new create edit update destroy]
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    authorize Post

    @page = params.fetch(:page, 0).to_i
    @category = params.fetch(:category, "All")
    @sortorder = params.fetch(:sort, 'desc')
    @query = 'created_at ' + @sortorder


    if @category == "All"
      if @page < 0
        redirect_to posts_path(page: 0)
      end
      @posts = Post.order(@query).offset(@page * POSTS_PER_PAGE).limit(POSTS_PER_PAGE)
    else
      if @page < 0
        redirect_to posts_path(page: 0, category: @category)
      end
        @posts = Post.order(@query).where(category: @category).offset(@page * POSTS_PER_PAGE).limit(POSTS_PER_PAGE)
    end
  end

  def search
    if params[:search].blank?
      redirect_to root_path
    else
      @parameter = params[:search].downcase
      @posts = Post.all.where("lower(body) LIKE :search OR lower(title) LIKE :search", search: "%#{@parameter}%")
    end
  end

  def show
    authorize @post

    @post = Post.find(params[:id])
  end

  def new
    authorize Post

    @post = Post.new
  end

  def create
    authorize Post

    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    authorize @post

    @post = Post.find(params[:id])
  end

  def update
    authorize @post

    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    authorize @post

    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :category, :picture)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
<p>
  By <strong><%= comment.author.name %></strong>
</p>

<p>
  <%= comment.body %>
</p>

<p>
  <% if policy(comment).destroy? %>
    <%= link_to 'Delete comment', [comment.post, comment],
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: 'btn btn-outline-dark'%>
  <% end %>
  <hr>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :body, class: 'form-label' %><br>
    <%= form.text_area :body, class: 'form-control' %>
  </p>
  <p>
    <%= form.submit "Post comment", class: 'btn btn-lg btn-outline-primary' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container">
      <% if !notice.nil? %>
        <div class="notice alert alert-success"><%= notice %></div>
      <% end %>
      <% if !alert.nil? %>
        <div class="alert alert-warning"><%= alert %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %><br>
    <%= form.text_field :title, class: 'form-control' %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :picture, class: 'form-label' %>
    <%= form.file_field :picture, class: 'form-control' %>
    <% post.errors.full_messages_for(:picture).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %><br>
    <%= form.text_area :body, class: 'form-control' %><br>
    <% post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :category, class: 'form-label' %><br>
    <%= form.select :category, ['Scientific', 'Politics', 'TV Series', 'Anime', 'Films', 'Technologies', 'Music', 'Sport', 'Other'],
                    selected: 'Scientific', class: 'form-select' %>
    <% post.errors.full_messages_for(:category).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Post", class: 'btn btn-lg btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
  <% if !Post.last.nil? %>
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic"><%= Post.last.title %></h1>
      <p class="lead mb-0">
        <%= link_to "Continue Reading...", post_path(Post.last) , class: 'text-white fw-bold' %>
      </p>
    </div>
  <% end %>
</div>

<div class="col-md-12 justify-content-center">
  <h2 class="pb-4 mb-4 fst-italic border-bottom">
    <%= @category %> Posts:
  </h2>
  <h3 class="pb-4 mb-4 fst-italic border-bottom">
    Order: <%= link_to "Newest", posts_path(sort: 'desc', category: @category), class: 'text-dark' %>
    <%= link_to "Oldest", posts_path(sort: 'asc', category: @category), class: 'text-dark' %>
  </h3>
  <% @posts.each do |post| %>
    <article class="blog-post">
      <h2 class="blog-post-title"><%= link_to post.title, post, class: 'text-decoration-none text-monospace text-dark' %></h2>
      <p class="blog-post-meta"> <%= post.created_at %> by <strong><%= post.author.name %></strong></p>
      <p>
        <%= image_tag(post.picture, width: 400) if post.picture.attached? %>
      </p>
      <p><%= post.body %></p>
      <p>Category: <%= link_to post.category, posts_path(category: post.category), class: 'btn btn-outline-dark mr-4' %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
          <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
        </svg> <%= post.comments.count %>
      </p>
    </article>
    <hr>
  <% end %>

  <%= link_to "Previous Page", posts_path(page: @page - 1, category: @category, sort: @sortorder), class: 'text-monospace text-dark' %> |
  <%= link_to "Next Page", posts_path(page: @page + 1, category: @category, sort: @sortorder), class: 'text-monospace text-dark' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/search.html.erb
<div class="col-md-12 justify-content-center">
  <h2 class="pb-4 mb-4 fst-italic border-bottom">
    Search results for '<%= @parameter %>':
  </h2>
  <% @posts.each do |post| %>
    <article class="blog-post">
      <h2 class="blog-post-title"><%= link_to post.title, post, class: 'text-decoration-none text-monospace text-dark' %></h2>
      <p class="blog-post-meta"> <%= post.created_at %> by
        <strong><%= link_to post.author.name, show_users_path(id: post.author.id), class: 'text-dark' %></strong>
      </p>
      <p>
        <%= image_tag(post.picture, width: 400) if post.picture.attached? %>
      </p>
      <p><%= post.body %></p>
      <p>Category: <%= link_to post.category, posts_path(category: post.category), class: 'btn btn-outline-dark mr-4' %>
        <a href="/posts/<%= post.id %>#comments" class="text-decoration-none text-dark">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
            <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
          </svg>
        </a> <%= post.comments.count %>
      </p>
    </article>
    <hr>
  <% end %>
</div>

app/views/posts/show.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%= @post.title %></h2>
  <p class="blog-post-meta"> <%= @post.created_at %> by
    <strong><%= link_to @post.author.name, show_users_path(id: @post.author.id), class: 'text-dark' %></strong>
  </p>  <p>
    <%= image_tag(@post.picture, width: 400) if @post.picture.attached? %>
  </p>
  <p><%= @post.body %></p>
  <p>Category: <%= link_to @post.category, posts_path(category: @post.category), class: 'btn btn-outline-dark' %></p>
</article>
<% if policy(@post).update? && policy(@post).destroy? %>
  <div class="btn-group" role="group" aria-label="Basic outlined example">
    <%= button_to "Edit", edit_post_path(@post), method: :get, class: 'btn btn-outline-secondary ms-2' %>
    <%= button_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>
<hr>
<h2 id="comments">Comments:</h2>
<%= render @post.comments %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/shared/_navbar.html.erb
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 mr-2 text-white text-decorations-none">
        <h3>Poster</h3>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 text-white">Home</a></li>
        <li><%= link_to "New", new_post_path, class: 'nav-link px-2 text-white' %></li>
        <li><a href="https://github.com/kwwiiGod/Poster" class="nav-link px-2 text-white">Github</a></li>
      </ul>

      <%= form_with url: search_posts_path, method: :get, class: 'col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3' do %>
        <%= search_field_tag :search, params[:search], placeholder: "Search...", class: 'form-control form-control-dark' %>
      <% end %>

      <div class="text-end">
        <span class="navbar-text">Welcome,
          <% if user_signed_in? %>
            <%= link_to current_user.name, show_users_path(id: current_user.id), class: 'text-white' %>
          <% else %>
            Guest
          <% end %>
        </span>
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, class: 'btn btn-outline-light me-2', method: :delete %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: 'btn btn-outline-light me-2' %>
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-warning' %>
        <% end %>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <%=link_to "All", posts_path(category: 'All'), class: 'p-2 link-secondary' %>
      <%=link_to "Music", posts_path(category: 'Music'), class: 'p-2 link-secondary' %>
      <%=link_to "Anime", posts_path(category: 'Anime'), class: 'p-2 link-secondary' %>
      <%=link_to "Scientific", posts_path(category: 'Scientific'), class: 'p-2 link-secondary' %>
      <%=link_to "Politics", posts_path(category: 'Politics'), class: 'p-2 link-secondary' %>
      <%=link_to "TV Series", posts_path(category: 'TV Series'), class: 'p-2 link-secondary' %>
      <%=link_to "Films", posts_path(category: 'Films'), class: 'p-2 link-secondary' %>
      <%=link_to "Technologies", posts_path(category: 'Technologies'), class: 'p-2 link-secondary' %>
      <%=link_to "Sport", posts_path(category: 'Sport'), class: 'p-2 link-secondary' %>
      <%=link_to "Other", posts_path(category: 'Other'), class: 'p-2 link-secondary' %>
    </nav>
  </div>
</div>



app/views/user/show.html.erb
<div class="col-md-12 justify-content-center">
  <h2 class="pb-4 mb-4 fst-italic border-bottom">
    <%= @user.name %>'s posts:
  </h2>
  <% @user.posts.each do |post| %>
    <article class="blog-post">
      <h2 class="blog-post-title"><%= link_to post.title, post, class: 'text-monospace text-dark' %></h2>
      <p class="blog-post-meta"> <%= post.created_at %> by
        <strong><%= link_to post.author.name, show_users_path(id: post.author.id), class: 'text-dark' %></strong>
      </p>
      <p>
        <%= image_tag(post.picture, width: 400) if post.picture.attached? %>
      </p>
      <p><%= post.body %></p>
      <p>Category: <%= link_to post.category, posts_path(category: post.category), class: 'btn btn-outline-dark mr-4' %>
        <a href="/posts/<%= post.id %>#comments" class="text-decoration-none text-dark">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
            <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
          </svg>
        </a> <%= post.comments.count %>
      </p>
    </article>
    <hr>
  <% end %>
</div>